name: Upload to COS

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/setup-python@v4
      # 设置 Python 版本
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      # 安装 COS SDK
      - name: Install COS SDK
        run: |
          pip install cos-python-sdk-v5
      # 配置 Tencent Cloud
      - name: Configure Tencent Cloud
        env:
          TENCENTCLOUD_SECRET_ID: ${{ secrets.SecretId }}
          TENCENTCLOUD_SECRET_KEY: ${{ secrets.SecretKey }}
        run: |
          pip install tencentcloud-sdk-python
          tencentcloud configure set secretId $TENCENTCLOUD_SECRET_ID
          tencentcloud configure set secretKey $TENCENTCLOUD_SECRET_KEY
      # 上传文件到 COS
      - name: Upload Files to COS
        env:
          COS_REGION: ap-shanghai  # 替换为实际地域
          COS_BUCKET: blog-1303450388  # 替换为存储桶名称
          COS_DEST_DIR: /  # 替换为目标路径
        run: |
          python -m coscmd config -a $TENCENTCLOUD_SECRET_ID -s $TENCENTCLOUD_SECRET_KEY -b $COS_BUCKET -r $COS_REGION
          coscmd upload -rs --delete -f ./ / --ignore "./.git/*"
